<h1 align="center">Fundamentos de Python para análisis de datos</h1>

## U1.01 Instalación y configuración del entorno de trabajo.

## U1.02 - Sintaxis Básica de Python

### Variables y tipos de datos

In [1]:
precio=1250.50 #float
cantidad=100 #integer
producto="Notebook" #string
activo=True #boolean
total=precio*cantidad

print(f'El total de la compra de {cantidad} unidades de {producto} es: ${total:.2f}')

El total de la compra de 100 unidades de Notebook es: $125050.00

### Estructuras de datos: listas, diccionarios y tuplas

In [2]:
ventas= [1200, 1500, 980, 2100, 1750]
print(f'El total de ventas es: ${sum(ventas):.2f}')
ventas.append(1600)

primera_venta = ventas[0]
total_registros = len(ventas)
ventas[1] = "A"

print(f'ventas: {ventas}, primera venta: {primera_venta}, total registros: {total_registros}')

El total de ventas es: $7530.00
ventas: [1200, 'A', 980, 2100, 1750, 1600], primera venta: 1200, total registros: 6

In [3]:
# Diccionarios son una colección no ordenada de pares clave-valor

cliente={
    "nombre": "Ana Gómez",
    "edad": 30,
    "ciudad": "Madrid",
    "compras": [2500, 3200, 1500]
}
cliente["compras"][1] = 5000
compras_cliente =cliente["compras"]
print(compras_cliente)

cliente.items()

[2500, 5000, 1500]

dict_items([('nombre', 'Ana Gómez'), ('edad', 30), ('ciudad', 'Madrid'), ('compras', [2500, 5000, 1500])])

In [4]:
# Tuplas: colecciones inmutables
coordenadas = (40.4168, -3.7038)
coordenadas[0]

fecha_cierre = (2026, 7, 27)
año, mes, dia = fecha_cierre
print(f'Año: {año}, Mes: {mes}, Día: {dia}')

Año: 2026, Mes: 7, Día: 27

## U1.03 - Estructuras de control y funciones

###	Condicionales (if, elif, else)

In [10]:
monto = 900
if monto >= 1500:
    print("Alto")
elif monto >= 1000:
    print("Medio")
else:
    print("Bajo")

Bajo

### Bucles (for, while) para iterar sobre colecciones

In [13]:
# Bucles for para iterar listas

ventas = [1200, 1500, 980, 2100, 1750]
total=0
for x in ventas:
    total += x
    print("Total de ventas es: ",total)

Total de ventas es:  1200
Total de ventas es:  2700
Total de ventas es:  3680
Total de ventas es:  5780
Total de ventas es:  7530

In [15]:
# Bucles for para iterar diccionarios

cliente={"nombre": "Juan", "ciudad": "Barcelona", "edad": 35}
for clave, valor in cliente.items():
    print(f'{clave}: {valor}')

nombre: Juan
ciudad: Barcelona
edad: 35

In [18]:
# Bucles while para condiciones

ventas_diarias = [500, 750, 600, 900, 1200]
objetivo = 2500
acumulado = 0
dia = 0
while acumulado < objetivo and dia < len(ventas_diarias):
    acumulado += ventas_diarias[dia]
    dia += 1
print(f'Objetivo alcanzado en {dia} días con un total de {acumulado} ventas')

Objetivo alcanzado en 4 días con un total de 2750 ventas

### Creación de funciones que reciben y retornan datos

In [22]:
def calcular_descuento(precio, descuento):
    """Calcula el precio final con descuento aplicado"""
    precio_descuento = precio - (precio * descuento / 100)
    precio_sin_descuento = precio
    return precio_descuento, precio_sin_descuento

precio_final = calcular_descuento(2000, 15)
print(f'El precio final con descuento es: ${precio_final[0]}, precio sin descuento: ${precio_final[1]} el ahorro es: ${precio_final[1]-precio_final[0]}')
print(calcular_descuento(2000, 15))

El precio final con descuento es: $1700.0, precio sin descuento: $2000 el ahorro es: $300.0
(1700.0, 2000)

### Manejo básico de errores con try/except

In [28]:
def calcular_margen(precio_venta, precio_costo):
    """Calcula el margen de ganancia"""
    try:
        margen = (precio_venta - precio_costo) / precio_costo * 100
        return round(margen, 2)
    except ZeroDivisionError:
        return "Error división por cero"
    except TypeError:
        return "Error: Tipo de dato no válido"
    except:
        return "Error desconocido"

#pruebas
print(calcular_margen(150, 100)) # 50.0
print(calcular_margen(150, 0)) # Error: Costo no puede ser cero
print(calcular_margen("150", 100)) # Error: Tipo de dato no válido

50.0
Error división por cero
Error: Tipo de dato no válido

## U1.04 - Primer contacto con datos

###  Importar pandas y leer un archivo CSV

In [9]:
import pandas as pd

df_ventas = pd.read_csv('ventas_enero.csv') #ruta del archivo CSV

### Exploración inicial: .head(), .info(), .shape

In [15]:
df_ventas.head(10) # Muestra las primeras filas del DataFrame

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,monto_total,region,vendedor
0,1139,2024-01-01,Tablet Samsung,Computadoras,1,431.35,431.35,Oeste,Juan Pérez
1,1048,2024-01-01,Disco SSD 1TB,Almacenamiento,5,125.12,625.60,Oeste,María López
2,1116,2024-01-01,Hub USB-C,Accesorios,7,35.32,247.24,Norte,Ana García
3,1114,2024-01-01,Disco SSD 1TB,Almacenamiento,6,122.03,732.18,Oeste,Pedro Sánchez
4,1030,2024-01-02,"Monitor LG 27""",Monitores,1,335.50,335.50,Oeste,Ana García
5,1175,2024-01-02,Memoria RAM 16GB,Componentes,2,73.61,147.22,Este,Ana García
6,1037,2024-01-03,Hub USB-C,Accesorios,1,36.26,36.26,Norte,Lucía Rodríguez
7,1046,2024-01-03,Hub USB-C,Accesorios,4,33.83,135.32,Oeste,Juan Pérez
8,1095,2024-01-03,Micrófono USB,Audio,4,55.95,223.80,Sur,Carlos Méndez
9,1094,2024-01-03,Webcam HD,Accesorios,9,45.74,411.66,Centro,María López

df_ventas.info() # Información general del DataFrame

In [16]:
filas, columnas = df_ventas.shape
print(f'El DataFrame tiene {filas} filas y {columnas} columnas')

El DataFrame tiene 200 filas y 9 columnas

df_ventas.info

In [17]:
df_ventas.info() #Información general del DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         200 non-null    int64
 1   fecha            200 non-null    str
 2   producto         200 non-null    str
 3   categoria        200 non-null    str
 4   cantidad         200 non-null    int64
 5   precio_unitario  200 non-null    float64
 6   monto_total      200 non-null    float64
 7   region           200 non-null    str
 8   vendedor         200 non-null    str
dtypes: float64(2), int64(2), str(5)
memory usage: 14.2 KB

### Entender la estructura de un DataFrame

In [18]:
df_ventas.columns #Nombres de las columnas del DataFrame

Index(['id_venta', 'fecha', 'producto', 'categoria', 'cantidad',
       'precio_unitario', 'monto_total', 'region', 'vendedor'],
      dtype='str')

In [19]:
df_ventas[['producto', 'categoria']].head()

         producto       categoria
0  Tablet Samsung    Computadoras
1   Disco SSD 1TB  Almacenamiento
2       Hub USB-C      Accesorios
3   Disco SSD 1TB  Almacenamiento
4  Monitor LG 27"       Monitores

In [20]:
cantidad_registros = len(df_ventas)
cantidad_columnas = len(df_ventas.columns)
print(f'El DataFrame tiene {cantidad_registros} registros y {cantidad_columnas} columnas')

El DataFrame tiene 200 registros y 9 columnas