In [1]:
import pandas as pd

df_ventas = pd.read_csv('ventas_trimestre.csv')
df_ventas.head()

,id_venta,fecha,vendedor,region,pais,producto,categoria,cantidad,precio_unitario,monto_total
0,1001,2024-12-21,carlos ruiz,NaN,Chile,Laptop Basic,Computación,9.0,800,7200.0
1,1002,2024-11-24,Carlos Ruiz,NaN,Ecuador,Webcam HD,Accesorios,4.0,60,240.0
2,1003,2024-12-29,juan perez,NaN,Colombia,Laptop Basic,Computación,6.0,800,4800.0
3,1004,2024-10-28,Pedro Castro,Sur,Peru,Teclado Mecánico,Accesorios,1.0,80,80.0
4,1005,2024-12-08,carlos ruiz,NaN,Peru,Webcam HD,Accesorios,6.0,60,360.0

In [4]:
registros, variables = df_ventas.shape
print(f"El DataFrame tiene {registros} registros y {variables} variables.")

El DataFrame tiene 400 registros y 10 variables.

In [5]:
df_ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         400 non-null    int64
 1   fecha            400 non-null    str
 2   vendedor         400 non-null    str
 3   region           287 non-null    str
 4   pais             391 non-null    str
 5   producto         400 non-null    str
 6   categoria        400 non-null    str
 7   cantidad         387 non-null    float64
 8   precio_unitario  400 non-null    int64
 9   monto_total      387 non-null    float64
dtypes: float64(2), int64(2), str(6)
memory usage: 31.4 KB

In [6]:
df_ventas.describe()

          id_venta    cantidad  precio_unitario   monto_total
count   400.000000  387.000000       400.000000    387.000000
mean   1200.500000    5.457364       296.275000   1493.578811
std     115.614301    2.847618       367.008498   2376.152389
min    1001.000000    1.000000        15.000000  -8000.000000
25%    1100.750000    3.000000        50.000000    160.000000
50%    1200.500000    6.000000        80.000000    480.000000
75%    1300.250000    8.000000       500.000000   2000.000000
max    1400.000000   10.000000      1200.000000  12000.000000